openapi: 3.0.0
info:
  title: NexCad Address Maintenance API
  description: SCSO NexCad address maintenance api
  contact:
    email: chughes@seminolesheriff.org
  license:
    name: Apache 2.0
    url: https://nexcad.seminolesheriff.org:8901
  version: 1.0.0
servers:
- url: https://virtserver.swaggerhub.com/chughes-506/NexCadAddressMaintenanceAPI/1.0.0
  description: SwaggerHub API Auto Mocking
- url: https://virtserver.swaggerhub.com/chughes-506/NexCadLogin/1.0.0
  description: SwaggerHub API Auto Mocking
- url: https://nexcad.seminolesheriff.org:8901/addressmaint/
  description: NexCad Address Maintenance API base path
paths:
  /GetAddresses:
    get:
      summary: Searches addresses
      description: Searches address information based on the provided parameters in the form
      parameters:
      - name: SoKey
        in: query
        description: pass SoKey to identify the requesting organization
        required: true
        style: form
        explode: true
        schema:
          type: string
      - name: PadNum
        in: query
        description: pass PadNum to identify the property number
        required: true
        style: form
        explode: true
        schema:
          type: string
      - name: PadDir
        in: query
        description: pass PadDir to identify the direction of the address
        required: true
        style: form
        explode: true
        schema:
          type: string
      - name: PadName
        in: query
        description: pass PadName to identigy the property type
        required: true
        style: form
        explode: true
        schema:
          type: string
      - name: PadStr
        in: query
        description: pass PadStr to identigy the street number or name
        required: true
        style: form
        explode: true
        schema:
          type: string
      - name: Location
        in: query
        description: Location request parameter
        required: false
        style: form
        explode: true
        schema:
          type: object
          format: object
      - name: BusSubDiv
        in: query
        description: Business sub-division
        required: false
        style: form
        explode: true
        schema:
          type: string
          format: string
      - name: DistBnd
        in: query
        description: District Boundary
        required: false
        style: form
        explode: true
        schema:
          type: string
          format: string
      - name: CsaBnd
        in: query
        description: CSA Boundary
        required: false
        style: form
        explode: true
        schema:
          type: string
          format: string
      - name: CityDist
        in: query
        description: City District
        required: false
        style: form
        explode: true
        schema:
          type: string
          format: string
      - name: CityCSA
        in: query
        description: City CSA
        required: false
        style: form
        explode: true
        schema:
          type: string
          format: string
      - name: Muni
        in: query
        description: Municipality
        required: false
        style: form
        explode: true
        schema:
          type: string
          format: string
      - name: CityCode
        in: query
        description: City Code
        required: false
        style: form
        explode: true
        schema:
          type: integer
          format: int32
      - name: City
        in: query
        description: City name
        required: false
        style: form
        explode: true
        schema:
          type: string
          format: string
      - name: AgencyCode
        in: query
        description: Agency Code
        required: false
        style: form
        explode: true
        schema:
          type: integer
          format: int32
      responses:
        "200":
          description: search results matching criteria
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/SOSitusIntersectionSearchInfo'
        "400":
          description: bad input parameter
        "401":
          description: unathorized action
        "408":
          description: Server timed out
        "500":
          description: An error occurred while processing your request
  /AddNewAddress:
    post:
      summary: Add a new address
      description: Adds a new address to the database
      operationId: AddNewAddress
      requestBody:
        description: Address object that needs to be added to the database
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/AddNewAddress_body'
        required: true
      responses:
        "200":
          description: Search results matching criteria
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/SOSitus'
        "400":
          description: Bad input parameter
        "401":
          description: Unathorized action
        "408":
          description: Server timed out
        "500":
          description: An error occurred while processing your request
components:
  schemas:
    SOSitusIntersectionSearchInfo:
      type: object
      properties:
        SoKey:
          type: string
          format: string
          example: "1234567"
        PadNum:
          type: integer
          format: int
          example: 1234
        PadDir:
          type: string
          format: string
          example: "NW, SW, E, N"
        PadName:
          type: string
          format: string
          example: "Home, Business, etc"
        PadStr:
          type: string
          format: string
          example: "First, Second, Elm St"
        Location:
          type: object
          format: string
          example: "2010 First St Lake Marty, Fl 32741"
        BusSubDiv:
          type: string
          format: string
          example: Business Sub Division
        DistBnd:
          type: string
          format: string
          example: 51 St and Gomor Rd
        CsaBnd:
          type: string
          format: string
          example: 51 St and Gomor Rd
        CityCSA:
          type: string
          format: string
          example: Seminole County Sherriff Office
        Muni:
          type: string
          format: string
          example: Lake Mary
        CityCode:
          type: integer
          format: int
          example: 601
        City:
          type: string
          format: string
          example: Lake Mary
        AgencyCode:
          type: integer
          format: int32
          example: 54
    SOSitus:
      type: object
      properties:
        SoKey:
          type: string
          example: "123"
        AgencyCode:
          type: string
          example: "20"
        BusSubDiv:
          type: string
          example: Lake Mary
        Parcel:
          type: string
          example: "123"
        Address:
          type: string
          example: 123 First St
        City:
          type: string
          example: Lake Mary
        CityCode:
          type: string
          example: "50"
        CityCSA:
          type: string
          example: Seminole County Sherriff Office
        CityDist:
          type: string
          example: Distrivt
        CsaBnd:
          type: string
          example: 51 St and Gomor Rd
        DistBnd:
          type: string
          example: 51 St and Gomor Rd
        Municipality:
          type: string
          example: Lake Mary
        PadNum:
          type: integer
          format: int
          example: 1234
        PadDir:
          type: string
          format: string
          example: "NW, SW, E, N"
        PadName:
          type: string
          format: string
          example: "Home, Business, etc"
        PadStr:
          type: string
          format: string
          example: "First, Second, Elm St"
        DomNbr:
          type: string
          example: "123"
        Multi:
          type: string
          example: "123"
        IntStr1:
          type: string
          example: First St
        IntStr2:
          type: string
          example: Second Ave
        XCoord:
          type: string
          example: "50"
        YCoord:
          type: string
          example: "50"
        Zip:
          type: string
          example: "12345"
        Inactive:
          type: boolean
          example: true
        NewSOKey:
          type: string
          example: 12345789true
        LockedBy:
          type: string
          example: CH123456
        UserCanEdit:
          type: boolean
          example: true
    AddNewAddress_body:
      type: object
      properties:
        SoKey:
          type: string
          example: "123"
        AgencyCode:
          type: string
          example: "20"
        BusSubDiv:
          type: string
          example: Lake Mary
        Parcel:
          type: string
          example: "123"
        Address:
          type: string
          example: 123 First St
        City:
          type: string
          example: Lake Mary
        CityCode:
          type: string
          example: "50"
        CityCSA:
          type: string
          example: Seminole County Sherriff Office
        CityDist:
          type: string
          example: Distrivt
        CsaBnd:
          type: string
          example: 51 St and Gomor Rd
        DistBnd:
          type: string
          example: 51 St and Gomor Rd
        Municipality:
          type: string
          example: Lake Mary
        PadNum:
          type: integer
          format: int
          example: 1234
        PadDir:
          type: string
          format: string
          example: "NW, SW, E, N"
        PadName:
          type: string
          format: string
          example: "Home, Business, etc"
        PadStr:
          type: string
          format: string
          example: "First, Second, Elm St"
        DomNbr:
          type: string
          example: "123"
        Multi:
          type: string
          example: "123"
        IntStr1:
          type: string
          example: First St
        IntStr2:
          type: string
          example: Second Ave
        XCoord:
          type: string
          example: "50"
        YCoord:
          type: string
          example: "50"
        Zip:
          type: string
          example: "12345"
        Inactive:
          type: boolean
          example: true
        NewSOKey:
          type: string
          example: 12345789true
        LockedBy:
          type: string
          example: CH123456
        UserCanEdit:
          type: boolean
          example: true
