openapi: 3.0.0
info:
  title: Address Maintenance API
  description: Address maintenance api
  contact:
    email: testemail@google.com
    
  version: 1.0.0
servers:
- url: https://virtserver.swaggerhub.com/chughes-506/NexCadAddressMaintenanceAPI/1.0.0
  description: SwaggerHub API Auto Mocking
- url: https://virtserver.swaggerhub.com/chughes-506/AddressMaintenanceAPI/1.0.0
  description: SwaggerHub API Auto Mocking
- url: https://virtserver.swaggerhub.com/chughes-506/Login/1.0.0
  description: SwaggerHub API Auto Mocking
- url: https://apiname.org:/addressmaint/
  description: API base path
paths:
  /GetAddresses:
    get:
      summary: Searches addresses
      description: Searches address information based on the provided parameters in the form
      parameters:
      - name: SoKey
        in: query
        description: Pass SoKey to identify the requesting organization
        required: true
        style: form
        explode: true
        schema:
          type: string
      - name: PadNum
        in: query
        description: Pass PadNum to identify the property number
        required: true
        style: form
        explode: true
        schema:
          type: string
      - name: PadDir
        in: query
        description: Pass PadDir to identify the direction of the address
        required: true
        style: form
        explode: true
        schema:
          type: string
      - name: PadName
        in: query
        description: Pass PadName to identify the property type
        required: true
        style: form
        explode: true
        schema:
          type: string
      - name: PadStr
        in: query
        description: Pass PadStr to identify the street number or name
        required: true
        style: form
        explode: true
        schema:
          type: string
      - name: Location
        in: query
        description: Pass Location parameter to identify the Locaioin
        required: false
        style: form
        explode: true
        schema:
          type: object
          format: object
      - name: BusSubDiv
        in: query
        description: Pass the BusSubDiv parameter to identify the Sub-Division
        required: false
        style: form
        explode: true
        schema:
          type: string
          format: string
      - name: DistBnd
        in: query
        description: Pass the DistBnd parameter to identify the  District Boundary
        required: false
        style: form
        explode: true
        schema:
          type: string
          format: string
      - name: CsaBnd
        in: query
        description: Pass the CsaBnd parameter to identify the CSA Boundary
        required: false
        style: form
        explode: true
        schema:
          type: string
          format: string
      - name: CityDist
        in: query
        description: Pass the CityDist parameter to identify the City District
        required: false
        style: form
        explode: true
        schema:
          type: string
          format: string
      - name: CityCSA
        in: query
        description: Pass the CityCSA parameter to identify the City CSA
        required: false
        style: form
        explode: true
        schema:
          type: string
          format: string
      - name: Muni
        in: query
        description: Pass the Muni parameter to identify the Municipality
        required: false
        style: form
        explode: true
        schema:
          type: string
          format: string
      - name: CityCode
        in: query
        description: Pass the CityCode parameter to identify the City Code
        required: false
        style: form
        explode: true
        schema:
          type: integer
          format: int32
      - name: City
        in: query
        description: Pass the City parameter to identify the City name
        required: false
        style: form
        explode: true
        schema:
          type: string
          format: string
      - name: AgencyCode
        in: query
        description: Pass the AgencyCode parameter to identify the Agency Code
        required: false
        style: form
        explode: true
        schema:
          type: integer
          format: int32
      responses:
        "200":
          description: search results matching criteria
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/SOSitusIntersectionSearchInfo'
        "400":
          description: bad input parameter
        "401":
          description: unathorized action
        "408":
          description: Server timed out
        "500":
          description: An error occurred while processing your request
  /AddNewAddress:
    post:
      summary: Add a new address
      description: Adds a new address to the database
      operationId: AddNewAddress
      requestBody:
        description: Address object that needs to be added to the database
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/AddNewAddress_body'
        required: true
      responses:
        "200":
          description: Search results matching criteria
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/SOSitus'
        "400":
          description: Bad input parameter
        "401":
          description: Unathorized action
        "408":
          description: Server timed out
        "500":
          description: An error occurred while processing your request
components:
  schemas:
    SOSitusIntersectionSearchInfo:
      type: object
      properties:
        SoKey:
          type: string
          format: string
          example: "1234567"
        PadNum:
          type: integer
          format: int
          example: 1234
        PadDir:
          type: string
          format: string
          example: "NW, SW, E, N"
        PadName:
          type: string
          format: string
          example: "Home, Business, etc"
        PadStr:
          type: string
          format: string
          example: "First, Second, Elm St"
        Location:
          type: object
          format: string
          example: "2010 First St Lake Marty, Fl 32741"
        BusSubDiv:
          type: string
          format: string
          example: Business Sub Division
        DistBnd:
          type: string
          format: string
          example: 51 St and Gomor Rd
        CsaBnd:
          type: string
          format: string
          example: 51 St and Gomor Rd
        CityCSA:
          type: string
          format: string
          example: Example CityCSA
        Muni:
          type: string
          format: string
          example: Lake Mary
        CityCode:
          type: integer
          format: int
          example: 601
        City:
          type: string
          format: string
          example: Lake Mary
        AgencyCode:
          type: integer
          format: int32
          example: 54
    SOSitus:
      type: object
      properties:
        SoKey:
          type: string
          example: "123"
        AgencyCode:
          type: string
          example: "20"
        BusSubDiv:
          type: string
          example: Lake Mary
        Parcel:
          type: string
          example: "123"
        Address:
          type: string
          example: 123 First St
        City:
          type: string
          example: Lake Mary
        CityCode:
          type: string
          example: "50"
        CityCSA:
          type: string
          example: Example CityCSA
        CityDist:
          type: string
          example: District
        CsaBnd:
          type: string
          example: 51 St and Gomor Rd
        DistBnd:
          type: string
          example: 51 St and Gomor Rd
        Municipality:
          type: string
          example: Lake Mary
        PadNum:
          type: integer
          format: int
          example: 1234
        PadDir:
          type: string
          format: string
          example: "NW, SW, E, N"
        PadName:
          type: string
          format: string
          example: "Home, Business, etc"
        PadStr:
          type: string
          format: string
          example: "First, Second, Elm St"
        DomNbr:
          type: string
          example: "123"
        Multi:
          type: string
          example: "123"
        IntStr1:
          type: string
          example: First St
        IntStr2:
          type: string
          example: Second Ave
        XCoord:
          type: string
          example: "50"
        YCoord:
          type: string
          example: "50"
        Zip:
          type: string
          example: "12345"
        Inactive:
          type: boolean
          example: true
        NewSOKey:
          type: string
          example: 12345789true
        LockedBy:
          type: string
          example: CH123456
        UserCanEdit:
          type: boolean
          example: true
    AddNewAddress_body:
      type: object
      properties:
        SoKey:
          type: string
          example: "123"
        AgencyCode:
          type: string
          example: "20"
        BusSubDiv:
          type: string
          example: Lake Mary
        Parcel:
          type: string
          example: "123"
        Address:
          type: string
          example: 123 First St
        City:
          type: string
          example: Lake Mary
        CityCode:
          type: string
          example: "50"
        CityCSA:
          type: string
          example: Example CityCSA
        CityDist:
          type: string
          example: District
        CsaBnd:
          type: string
          example: 51 St and Gomor Rd
        DistBnd:
          type: string
          example: 51 St and Gomor Rd
        Municipality:
          type: string
          example: Lake Mary
        PadNum:
          type: integer
          format: int
          example: 1234
        PadDir:
          type: string
          format: string
          example: "NW, SW, E, N"
        PadName:
          type: string
          format: string
          example: "Home, Business, etc"
        PadStr:
          type: string
          format: string
          example: "First, Second, Elm St"
        DomNbr:
          type: string
          example: "123"
        Multi:
          type: string
          example: "123"
        IntStr1:
          type: string
          example: First St
        IntStr2:
          type: string
          example: Second Ave
        XCoord:
          type: string
          example: "50"
        YCoord:
          type: string
          example: "50"
        Zip:
          type: string
          example: "12345"
        Inactive:
          type: boolean
          example: true
        NewSOKey:
          type: string
          example: 12345789true
        LockedBy:
          type: string
          example: CH123456
        UserCanEdit:
          type: boolean
          example: true
